docs(capter-v): add cargo.md
evilfactorylabs/belajar-rust pull request #5
Opened 2020-06-19 16:26 UTC by ri7nz

2020-06-20 04:26 UTC, adiatma requested changes

2020-06-20 04:26 UTC, adiatma commented on content/capter-5/cargo.md
> +```
```bash
cargo new my-project
Created binary (application) `my-project` package
ls my-project
Cargo.toml
src
ls my-project/src
main.rs
```

2020-06-20 04:26 UTC, adiatma commented on content/capter-5/cargo.md
> +_src/lib.rs_
```rust
// src/lib.rs
pub mod restaurant {
   pub fn hello(name: String) -> String {
       name
   }
}
```

2020-06-20 04:26 UTC, adiatma commented on content/capter-5/cargo.md
> +_src/main.rs_
```rust
// src/main.rs
extern crate my_lib;
use my_lib::restaurant;
fn main() {
   let adi = restaurant::hello(String::from("adi"));
   println!("{}", adi);
}
```

2020-06-20 04:26 UTC, adiatma commented on content/capter-5/cargo.md
> +> _src/lib.rs_
```rust
// src/lib.rs
pub mod restaurant {
   pub fn hello(name: String) -> String {
       name
   }
}
pub fn call_directly() {
   // Absolute Path
   crate::restaurant::hello();
   // Relative Path
   self::restaurant::hello();
}
```

2020-06-20 04:26 UTC, adiatma commented on content/capter-5/cargo.md
> +###
remove `###`

2020-06-20 04:26 UTC, adiatma commented on content/capter-5/cargo.md
> +```
```rust
pub mod restaurant {
   pub fn hello(name: String) -> String {
       name
   }
}

use crate::restaurant;

pub fn call_hello_from_restaurant() {
   restaurant::hello()
}
```

2020-06-20 11:23 UTC, ri7nz commented on content/capter-5/cargo.md
> +```
updated

2020-06-20 11:23 UTC, ri7nz commented on content/capter-5/cargo.md
> +###
updated

2020-06-20 11:23 UTC, ri7nz commented on content/capter-5/cargo.md
> +> _src/lib.rs_
updated

2020-06-20 18:58 UTC, adiatma commented
Format `##` kaga ke baca kayaknya pak @ri7nz  di markdownnya, makanya kemarin ku hapus wkwk

2020-06-20 19:05 UTC, ri7nz commented
@adiatma  `##` format H2 kan ya, ngk kebaca diweb atau dimana nih ?

2020-06-20 19:07 UTC, adiatma commented
> @adiatma `##` format H2 kan ya, ngk kebaca diweb atau dimana nih ?

Iya `h2` gak kebaca di web

2020-06-20 19:12 UTC, ri7nz commented
@adiatma 

bisa harusnya 

https://handbook.evilfactory.id/evangelist/2-voice-and-tone
https://github.com/evilfactorylabs/handbook/blob/master/content/evangelist/2-voice-and-tone.md#perbedaan-suara--nada

2020-06-20 19:18 UTC, adiatma commented
> @adiatma
> 
> bisa harusnya
> 
> https://handbook.evilfactory.id/evangelist/2-voice-and-tone
> https://github.com/evilfactorylabs/handbook/blob/master/content/evangelist/2-voice-and-tone.md#perbedaan-suara--nada

Hmm, iya ya, wait, ku coba lagi Pak..

2020-06-22 12:25 UTC, ri7nz commented
Need review @adiatma  @kevanantha

2020-06-22 13:42 UTC, adiatma requested changes
cc @ri7nz

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +## Chapter V - Cargo
```suggestion

```

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +### _Mengenal Packages, Crates, & Module_
```suggestion
_Mengenal Packages, Crates, & Module_
```

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +### _Packages & Crates_
```suggestion
_Packages & Crates_
```

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +```
```suggestion
```bash
```

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +### _Modules_
```suggestion
_Modules_
```

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +```
```suggestion
```rust
```

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +```
```suggestion
```rust
```

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +### _Paths_ untuk mereferensi ke sebuah item di dalam _module_
```suggestion
_Paths_ untuk mereferensi ke sebuah item di dalam _module_
```

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +```
```suggestion
```rust
```

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +### Memahami **_use_**
```suggestion
Memahami **_use_**

```

2020-06-22 13:42 UTC, adiatma commented on content/chapter-5/cargo.md
> +```
```suggestion
```rust
```

2020-06-22 13:42 UTC, adiatma commented on config.js
> +    forcedNavOrder: ['/chapter-1', '/chapter-2', '/chapter-3'],
```suggestion
    forcedNavOrder: ['/chapter-1', '/chapter-2', '/chapter-3', '/chapter-4', '/chapter-5'],
```

2020-06-22 16:58 UTC, kevanantha requested changes

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +* **_Crates_** adalah _root_ dari beberapa module, dan function yang berelasi.
italic for module ana function @ri7nz

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +* **_Modules_** & **_use _** untuk mengontrol ruang lingkup dan privasi dari _paths _atau bagian dari sistem _module_.
`_paths_`

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +* **_Paths_** adalah sebuah file yang terisolasi untuk mengelompokan _function_ dan _module_.
mengelompokkan

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +Pada contoh diatas perintah `cargo new my-project` akan menghasilkan _package_ `my-project` didalamnya terdapat direktori `src` yang berisi file `src/main.rs` dan file `Cargo.toml`  yang berisi infor
```suggestion
Pada contoh diatas perintah `cargo new my-project` akan menghasilkan _package_ `my-project` didalamnya terdapat direktori `src` yang berisi file `src/main.rs` dan file `Cargo.toml` yang berisi informasi paket pustaka yang kita gunakan, mirip seperti `package.json` jika menggunakan _NodeJS_.
```

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +Setelah membahas tentang _package_ dan _crate_ hal selanjutnya adalah _modules,_ kita akan bahas sedikit tentang bagian - bagian dari sebuah _module_. Hal yang pertama adalah _paths_ yang digunakan u
```suggestion
Setelah membahas tentang _package_ dan _crate_ hal selanjutnya adalah _modules,_ kita akan bahas sedikit tentang bagian-bagian dari sebuah _module_. Hal yang pertama adalah _paths_ yang digunakan untuk mengelompokkan sebuah fungsi-fungsi dan _module_ dalam sebuah file. Selanjutnya ada **_use_** yang merupakan _keyword_ untuk memanggil atau membawa sebuah _path_ kedalam _scope_ yang berbeda, dan **_pub keyword_** yang akan membuat sebuah _item_ menjadi publik agar dapat diakses di _scope_ yang berbeda.
```

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +_Modules_ membuat kita mudah untuk mengorganisasikan sebuah _function_ berdasarkan fungsinya dan dapat digunakan berkali - kali untuk meminimalisir pekerjaan kita.
```suggestion
_Modules_ membuat kita mudah untuk mengorganisasikan sebuah _function_ berdasarkan fungsinya dan dapat digunakan berkali-kali untuk meminimalisir pekerjaan kita.
```

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +Oke, untuk selanjutnya kita akan membuat sebuah paket _library_ di Rust, silahkan ketik perintah `cargo new --lib my-lib` yang secara otomatis akan membuat skeleton project yang _support_ untuk mener
```suggestion
Oke, untuk selanjutnya kita akan membuat sebuah paket _library_ di Rust, silakan ketik perintah `cargo new --lib my-lib` yang secara otomatis akan membuat _skeleton project_ yang _support_ untuk menerapkan konsep _library_, dengan _option_ `--lib` file yang di _generate_ dalam direktori `src` adalah `src/lib.rs` berbeda dengan tanpa menggunakan `--lib`.
```

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +Pada contoh kode diatas terdapat sebuah _module_ restaurant dengan _function_ `hello()` di dalamnya. _Keyword_ **_pub_** digunakan untuk membuat _module_ tersebut bisa diakses dari scope atau _path_
```suggestion
Pada contoh kode diatas terdapat sebuah _module_ _**restaurant**_ dengan _function_ `hello()` di dalamnya. _Keyword_ **_pub_** digunakan untuk membuat _module_ tersebut bisa diakses dari _scope_ atau _path_ yang berbeda.
```

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +Untuk menguji _module_ restaurant tersebut silahkan buat file `main.rs`, di dalam direktori `src/main.rs` isi dengan kode dibawah ini.
```suggestion
Untuk menguji _module_ _**restaurant**_ tersebut silakan buat file `main.rs`, di dalam direktori `src/main.rs` isi dengan kode dibawah ini.
```

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +Pada kode diatas kode `extern crate my_lib` bertujuan untuk mengambil _module_ yang berada di _paths_ `lib.rs` yang merupakan root component, kemudian ada _keyword_ `use` tujuannya untuk membawa _mod
```suggestion
Pada kode diatas, kode `extern crate my_lib` bertujuan untuk mengambil _module_ yang berada di _paths_ `lib.rs` yang merupakan _root component_, kemudian ada _keyword_ `use` tujuannya untuk membawa _module_ _**restaurant**_ yang ada pada _package_ `my_lib`.
```

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +Dari kedua _absolute_ dan _relative_ _paths_ diatas selanjutnya untuk mengakses module secara spesifik bisa menggunakan semicolons `(::)` biar lebih `clear` berikut ada contohnya.
```suggestion
Dari kedua _absolute_ dan _relative_ _paths_ diatas selanjutnya untuk mengakses _module_ secara spesifik bisa menggunakan _semicolons_ `(::)` biar lebih `clear` berikut ada contohnya.
```

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +_Keyword_ **_pub_** yang terdapat di awal _module_ dan _function_ bertujuan untuk mengekspos _module_ dan _function_ agar bisa diakses di luar _scope_, karena secara default module dan function di Ru
```suggestion
_Keyword_ **_pub_** yang terdapat diawal _module_ dan _function_ bertujuan untuk mengekspos _module_ dan _function_ agar bisa diakses di luar _scope_, karena secara _default module_ dan _function_ di Rust bersifat _private_.
```

2020-06-22 16:58 UTC, kevanantha commented on content/chapter-5/cargo.md
> +Pada kode diatas syntax kode `use crate::restaurant;`  digunakan untuk mengambil module restaurant dari **_root module_** dengan menggunakan cara  **_absolute paths._**
```suggestion
Pada kode diatas, _syntax_ kode `use crate::restaurant;` digunakan untuk mengambil _module restaurant_ dari **_root module_** dengan menggunakan cara  **_absolute paths._**
```

2020-06-22 17:00 UTC, kevanantha commented
reviewed cc @ri7nz

2020-06-24 13:35 UTC, merged